x=open("Hai.txt","w")
x.write("Hai, How r u ??")
x.close()
x=open("Hai.txt","rt")
print(x.read())
x.close()
x=open("Hai.txt","a")
x.write("How do you do??")
x.close()
x=open("Hai.txt","rt")
print(x.read())
x.close()